-- Insertar proyectos individualmente
INSERT OR IGNORE INTO projects (id, title, abstract, keywords, introduction, methodology, owner_id, is_public, status, start_date, end_date, institution, funding_source, budget, project_code) VALUES 
(2, 'Implementación de Tecnología Blockchain para Trazabilidad en Cadenas de Suministro Agroindustriales Colombianas', 'Desarrollo de una plataforma basada en tecnología blockchain para garantizar la trazabilidad, transparencia y autenticidad en las cadenas de suministro del sector agroindustrial colombiano', 'blockchain, trazabilidad, cadena de suministro, agroindustria', 'Colombia es uno de los principales exportadores agrícolas de América Latina', 'Se desarrollará una arquitectura blockchain híbrida utilizando Hyperledger Fabric', 2, 1, 'ACTIVE', '2024-02-01', '2024-12-31', 'Universidad EAFIT - Departamento de Ingeniería de Sistemas', 'Ministerio de Agricultura y Desarrollo Rural', 720000000.00, 'CTeI-BLOCK-AGR-002');

INSERT OR IGNORE INTO projects (id, title, abstract, keywords, introduction, methodology, owner_id, is_public, status, start_date, end_date, institution, funding_source, budget, project_code) VALUES 
(3, 'Red de Sensores IoT para Monitoreo Ambiental y Gestión Inteligente de Recursos Urbanos', 'Diseño e implementación de una red integrada de sensores IoT para el monitoreo en tiempo real de variables ambientales urbanas', 'IoT, ciudades inteligentes, monitoreo ambiental, sensores', 'Las ciudades intermedias de Colombia enfrentan desafíos crecientes relacionados con la calidad ambiental', 'Metodología de investigación aplicada con enfoque experimental', 3, 1, 'DEVELOPMENT', '2024-03-15', '2025-03-15', 'Universidad de Caldas - Facultad de Ingeniería', 'Alcaldía de Manizales - Convenio Especial', 650000000.00, 'CTeI-IOT-CITY-003');

INSERT OR IGNORE INTO projects (id, title, abstract, keywords, introduction, methodology, owner_id, is_public, status, start_date, end_date, institution, funding_source, budget, project_code) VALUES 
(4, 'Entornos de Realidad Virtual Inmersiva para la Enseñanza de Química Orgánica en Educación Superior', 'Creación de laboratorios virtuales inmersivos utilizando tecnologías de realidad virtual para la enseñanza de química orgánica', 'realidad virtual, educación superior, química orgánica', 'La enseñanza de química orgánica presenta desafíos únicos debido a la naturaleza abstracta de las estructuras moleculares', 'Metodología de diseño centrado en el usuario con desarrollo iterativo', 2, 1, 'ACTIVE', '2024-01-20', '2024-11-30', 'Universidad Javeriana - Facultad de Ciencias', 'MinEducación - Convocatoria Innovación Educativa', 480000000.00, 'CTeI-VR-EDU-004');

INSERT OR IGNORE INTO projects (id, title, abstract, keywords, introduction, methodology, owner_id, is_public, status, start_date, end_date, institution, funding_source, budget, project_code) VALUES 
(5, 'Análisis Genómico Computacional para Identificación de Biomarcadores en Cáncer Colorrectal en Población Colombiana', 'Desarrollo de pipelines bioinformáticos para el análisis de datos genómicos masivos orientados a la identificación de biomarcadores específicos', 'bioinformática, genómica, cáncer colorrectal, biomarcadores', 'El cáncer colorrectal presenta particularidades genómicas específicas según la población', 'Metodología de análisis bioinformático con pipeline automatizado', 1, 1, 'PLANNING', '2024-05-01', '2025-04-30', 'Universidad de Antioquia - Facultad de Medicina', 'Colciencias - Programa Nacional de Biotecnología', 920000000.00, 'CTeI-BIOINF-005');

INSERT OR IGNORE INTO projects (id, title, abstract, keywords, introduction, methodology, owner_id, is_public, status, start_date, end_date, institution, funding_source, budget, project_code) VALUES 
(6, 'Optimización de Sistemas Fotovoltaicos Mediante Algoritmos de Inteligencia Artificial para Condiciones Climáticas del Trópico Colombiano', 'Investigación orientada al desarrollo de algoritmos de optimización basados en inteligencia artificial para maximizar la eficiencia de sistemas fotovoltaicos', 'energía solar, fotovoltaico, inteligencia artificial, optimización', 'Colombia tiene un potencial significativo en energía solar debido a su ubicación ecuatorial', 'Metodología experimental con simulación computacional', 3, 1, 'ACTIVE', '2024-04-10', '2025-04-10', 'Universidad Nacional - Facultad de Ingeniería', 'MinEnergía - Programa FENOGE', 780000000.00, 'CTeI-SOLAR-006');