name = "ctei-manager-local"
compatibility_date = "2025-09-11"
pages_build_output_dir = "./dist"

compatibility_flags = [
  "nodejs_compat"
]

[[d1_databases]]
binding = "DB"
database_name = "ctei-manager-local"
database_id = "local-dev"

[env.local]
[[env.local.d1_databases]]
binding = "DB"
database_name = "ctei-manager-local"
database_id = "local-dev"